
resolver: lts-17.5

packages:
- ./sandwich
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

- ./sandwich-demos

- ./demos/demo-basic
- ./demos/demo-command-line-args
- ./demos/demo-contexts
- ./demos/demo-context-dependencies
- ./demos/demo-context-nested-dependencies
- ./demos/demo-custom-exceptions
- ./demos/demo-discover
- ./demos/demo-landing
- ./demos/demo-paralleln
- ./demos/demo-quickcheck
- ./demos/demo-slack
- ./demos/demo-timing
- ./demos/demo-timing-parallel
- ./demos/demo-tui
- ./demos/demo-webdriver
- ./demos/demo-webdriver-landing
- ./demos/demo-webdriver-pool
- ./demos/demo-webdriver-positioning
- ./demos/demo-webdriver-video

extra-deps:
# Because upstream hs-webdriver has a few bugs and seems unmaintained
- git: https://github.com/codedownio/hs-webdriver
  commit: 96400ea0ba6ef118033d6a727ef4f57c31a187ca
