name:                demo-quickcheck
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- sandwich
- sandwich-quickcheck
- string-interpolate
- time
- QuickCheck

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-quickcheck:
    main: Main.hs
    source-dirs: app
