name:                demo-webdriver-landing
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- filepath
- lifted-base
- sandwich
- sandwich-webdriver
- string-interpolate
- time
- webdriver

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-webdriver-landing:
    main: Main.hs
    source-dirs: app
